### ISSUE TITLE
nb 8.1, sec 1.2.1

### ISSUE THREAD

**Issue by dg7692** [innovationOUtside/tm129-robotics2020#119]
Receiving the following warning message:

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

Unclear whether this is to be expected (in which case need to add a note for students), or whether the warning needs fixing.

**Comment by psychemedia** [comment]
I think pickle is *really* sensitive to the version you use pickling... 

(Also, it'd be really useful to know which cell the issue arose with. I found it, but not immediately, because it's not explicitly called (it's inside joblib)..;-)
