### ISSUE TITLE
Typo section 1.2.2

### ISSUE THREAD

**Issue by dg216** [innovationOUtside/tm129-robotics2020#138]
Student has spotted a typo

In section 1.2.2

"When you run the program in the simulator, the robot should move forwards quickly for one second and then stop. "

I'm not sure if I'm missing something, mine runs for three seconds, and it looks like that's what the code says:

 # Program actions

left_motor.on(SpeedPercent(25))

right_motor.on(SpeedPercent(25))

# Wait here for 3 seconds...

time.sleep(3)

**Comment by psychemedia** [comment]
This is an issue to do with the simulator that we should turn into a teaching point:

>Inside the simulator is a clock that ticks time, incrementing the clock by 1 each time an "event loop" that manages the simulator is called (nominally, 30 times a second, which is to say, at 30 fps (frames per second)). The event loops checks the sensors and motors, updates the robot position, and animates the robot on screen. The robot's position is calculated by looking at the simulator clock time and seeing how far the robot should have moved in 1 tick of simulator time.
>
>The time function, as used by the "on for" command, runs in real time, not simulator clock time.
>
>If the event loop is slow in real time to calculate, then the interaction between simulator clock time, and real time, can get confused. 
>
>So it seems that my animation loop is taking longer than 1/30 s to calculate, which means that 1 second of simulator time (30 iterations of the event loop) will take longer than 1 second of actual time to calculate. So the simulator is calculating how far the robot should have moved in 1 tick of simulator time, but that takes longer to calculate than 1/30 s of real time. The on_for command is working in real time, which is running faster than the simulator clock time.
>
>Elements of this are picked up on in notebook 06.3 Keeping track of distance.ipynb .
