### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by psychemedia** [innovationOUtside/tm129-robotics2020#139]
- [x] 02.1 /  1.2.2 "When you run the program in the simulator, the robot should move forwards quickly for one second and then stop" - time sis set to 3 seconds
- [x] 02.1 /  1.3.1 Reference to move button
- [x] 02.1 / 1.3.4 Activity — Predicitng 
- [x] 07.1 *compaies*
- [x] several examples of *the the* throughout

**Comment by psychemedia** [comment]
Report typos in unspecified notebook:

> "The dataframe is a powerful data structure that allows us to represent and work with tabular datasets. In certain repsoects, you might think of is providing a code powered equivalent to a spreadsheet application such as Microsfot Excel.

**Comment by psychemedia** [comment]
"Move button" references:

- [ ] Week 2 / 2.1
- [ ] Week 4 / 4.3
Current workaround is:

> There is a button in the simulator Positioning panel that I think is supposed to reset the position to the default position associated with the current background...

**Comment by jdarch** [comment]
There's a typo in the README_FIRST.ipynb file:

"Welcome **the** the TM129 Robotics Block"

should be

"Welcome to the TM129 Robotics Block"
