### ISSUE TITLE
Week 1 content issues; Notebook 01.3

### ISSUE THREAD

**Issue by dg7692** [innovationOUtside/tm129-robotics2020#63]
Notebook 01.3, section 3.1; in the introduction, the image and paragraphs below the image should be removed, as that content is better covered elsewhere

**Comment by psychemedia** [comment]
Removed, or moved?

**Comment by dg7692** [comment]
The text I think can definitely be removed - students don't need to know anything about backgrounds or obstacles at this point, and it's well introduced later. The image could be shifted down to the start of section 3.3 to give a sense of what the simulator looks like before they load it up.

**Comment by psychemedia** [comment]
I'm not sure I'm seeing the same thing as you? 

![image](https://user-images.githubusercontent.com/82988/95576597-a0f03b00-0a28-11eb-8a12-0d4d89a5a2d8.png)

I think this works?

**Comment by dg7692** [comment]
This is what I see; it's more a question of flow as this image and the subsequent paragraphs sit between a discussion of EV3, the background cell on simulators and then another section on the EV3 brick. If could be shifted down an integrated into the opening of section 3.3 which I think could improve the flow.

Also not a major concern; could stay where it is if you have strong feelings about it.
