### ISSUE TITLE
Week 1 content issue; Notebook 01.3, section 3.3.2

### ISSUE THREAD

**Issue by dg7692** [innovationOUtside/tm129-robotics2020#64]
Notebook 01.3, section 3.3.2; in the code cell, insert a comment above %%sim_magic_preloaded that states something like # magic code to download the code in this cell to the simulator

**Comment by psychemedia** [comment]
If you add a comment above a %%cell_magic, it raises an error. The cell magic MUST staat with %%.

I will add a note to that effect.
