### ISSUE TITLE
Week 1 content: Use of Appendices

### ISSUE THREAD

**Issue by dg7692** [innovationOUtside/tm129-robotics2020#67]
Two points here:

1. I don't think the notebook architecture appendix needs to be included as that content is covered sufficiently elsewhere

2. I wondered about moving all of the appendices (week 1 and 3) into a "reference doc" notebook folder that sits separately from the weeks.

**Comment by psychemedia** [comment]
A reference directory (number 99.) might make sense?

**Comment by dg7692** [comment]
Sounds good to me.
