### ISSUE TITLE
Docker content issue

### ISSUE THREAD

**Issue by dg7692** [innovationOUtside/tm129-robotics2020#78]
00_FOR_VLE and 00_NOTES_FOR_TUTORS should no longer be contained in the version we are shipping out to students.

**Comment by psychemedia** [comment]
There's a lot of cruft still hanging around. I need to do some housekeeping but I also need to get stuff finished. I'm taking next few days off hopefully (definitely from pm tomorrow).; will be back to this next week.

**Comment by dg7692** [comment]
👍
